### ISSUE TITLE
Residual identification in asjp code

### ISSUE THREAD

**Issue by erathorn** [lingpy/lingpy#173]
Hi everyone,

it seems to me that the identification of residuals with strings in asjp-format does not work properly. If I try to align the following four words `'kwantita', 'kwati8a83', 'kantitate', 'kanti8a8'` in a multiple alignment using lingpy. I get the result below. To me, the `83`in the second row of the alignment should be two residuals instead of one.

    ['k', 'w', 'a', 'n', 't', 'i', 't', 'a', u'-', u'-'],
    ['k', 'w', 'a', u'-', 't', 'i', '8', 'a', '83', u'-'], #This line is wrong
    ['k', u'-', 'a', 'n', 't', 'i', 't', 'a', 't', 'e'],
    ['k', u'-', 'a', 'n', 't', 'i', '8', 'a', '8', u'-']]

The alignment is done by the following piece of code:

    import lingpy as lp

    align = lp.Multiple(words, merge_vowels = False)
    align.lib_align(model="asjp")

EDIT: This also happens for coombinations like `'35'` (`'d3z35ar'`) or `38` (`'mon38'`). So it seems to be a general problem regarding the usage of numbers in asjp code.

**Comment by erathorn** [comment]
To avoid this problem I translated the origninal ASJP to Lingpy ASJP, i.e `'e'` to `'I'` and `'5'` to `'H'`. But this gives me a problem with a lot of other doubling of residuals, i.e. `'ii'` ,`'aa'` ,or `'ss'` are making trouble.

**Comment by LinguList** [comment]
We have a couple of problems here, but first of all, note that I can't replicate your code with lingpy proper:

```python
>>> from lingpy import *
>>> rc(schmema='asjp')
>>> m = Multiple(['kwantita', 'kwati8a83', 'kantitate', 'kanti8a8'])
>>> m.prog_align()
>>> print(m)
k	w	a	n	t	i	t	-	-	a
k	w	a	-	t	i	8	a	8	3
k	-	a	n	t	i	t	a	t	e
k	-	a	n	t	i	8	a	8	-
```
Did you switch the schema in rc to asjp?

Now, regarding the internal asjp vs. external asjp:

it's a general problem: we need to use some internal asjp in order to avoid confusion with reserved characters, like "X". Also, ASJP doesn't have tone marks, but we want to have them, since we want to use ASJP for IPA sequences as well, which potentially have tones, so I added them to the alphabet. 

When preparing the ASJP alphabet, I didn't introduce certain symbols, like the "!", since it was not relevant by then, since I never had a benchmark dbase with clicks. 

Furthermore, certain letters are not very well described in the original paper, so I missed them, or even failed to include them correctly. An other reason is also, that the ASJP in lingpy is based on the paper by [Brown et al. 2013](http://bibliography.lingpy.org?key=Brown2013). I used the alphabet they gave me by then, since I wanted to have their correspondence-frequencies to be included in the ASJP scoring function. For my own purposes, this always was sufficient, since the mapping of IPA to this alphabet is never problematic. I recently discovered, however, that not all sounds were covered in my matrix.

It is possible, that this really leads to problems at some point. There may be unrecognized characters, or something else. So far, however, I didn't have the problems you mentioned above. So the question to be asked here initially is really: did you not switch to ASJP-schema using
```python
>>> lingpy.rc(schema="asjp")
```
It seems to me, you did not, since I just doublechecked, and it yields the code you mention:

```python
>>> from lingpy import *
>>> m = m = Multiple(['kwantita', 'kwati8a83', 'kantitate', 'kanti8a8'])
>>> print(m)
k	w	a	n	t	i	t	a	-	-
k	w	a	-	t	i	8	a	83	-
k	-	a	n	t	i	t	a	t	e
k	-	a	n	t	i	8	a	8	-
```
That this happens, is expected, since both 8 and 3 are labeled as tone-markes, and they will be just treated as a tone.

**Comment by LinguList** [comment]
BTW: to check the current settings for *segmentation*, please consult the function ipa2tokens (described on the website, also in sequence/sound_classes.py). This is the core of all alignment in which no *segmented* sequence is passed to the algorithm

If you want to provide your manual segmentations, just prepare them, and store them as strings separated by a comma:

```python
>>> a = 'b l a m'
```

If you pass these strings to Multiple, but also to other algorithms (define an extra "TOKENS" column in your wordlist files prior to loading them!), these won't be touched by lingpy. If you don't do this, lingpy segmentizes itself, and this may well lead to your unexpected output.

```python
>>> ipa2tokens('kanti83')
['k', 'a', 'n', 't', 'i', '83']
```

vs.

```python
>>> ipa2tokens('k a n t i 8 3')
['k', 'a', 'n', 't', 'i', '8', '3']
```

Closing this issue now, since it seems it is a handling issue rather than a software issue. I noted, however, that we need to increase the documentation of lingpy in order to avoid confusion among the users. Thanks a lot for bringing this up @erathorn ! And sorry for my late reply.
