### ISSUE TITLE
lingpy functionality as UNIX commands

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#176]
Some of the functionality of LingPy would be worthwhile having available as [UNIX commands](https://en.wikipedia.org/wiki/Pipeline_%28Unix%29), i.e.

- read from `stdin`
- write from `stdout`
- write errors to `stderr`

Relevant functionality:

- segmentation
- cognate detection

**Comment by LinguList** [comment]
Definitely, this would then feed into some kind of a workflow. Should this be done in form of typical python scripts which read in commandline argumetns with dashes and the like?

I posted one example (very rubbishly done) under this [gist](https://gist.github.com/LinguList/7612513). It reads in ASJP and outputs cognate judgments in various formats. 

The crucial question would be: where to assemble these scripts? They are not part of lingpy-propoer, but should maybe included in some LingPY-cookbook facility? Or is it even possible to get this via the library itself?

**Comment by xrotwang** [comment]
I think some commands should be distributed with the library as [console scripts](http://python-packaging.readthedocs.org/en/latest/command-line-scripts.html#the-console-scripts-entry-point)

**Comment by LinguList** [comment]
cool, didn't know that that existed. In that case, I would also know where to put the ASJP-script I wrote. It's somehow quite useful, since it gives one immediately all identifiable cognate sets for a given language family...

And of course, for segmentation, and other things, this would also be very useful.

**Comment by xrotwang** [comment]
The subcommand paradigm for command line interfaces seems well established by now (with `git` as the most famous example, but also `pip`, etc.). So maybe we should install a single `lingpy` command with the package, which provides commonly used, self-contained functionality as subcommands, following [this recipe](http://chase-seibert.github.io/blog/2014/03/21/python-multilevel-argparse.html).

**Comment by LinguList** [comment]
This sounds like a good idea. A major challenge from the conceptional side will be the question to which degree all the available parameters can or should be addressed (compare all the different ways you can handle lexstat, and not evan half of it is documented). But we could start on a low level and decide on the most important points, and from there start getting a bit more complex. 

BTW, some long time ago I wrote a standalone script which uses lingpy to compute cognate sets for asjp data in tabular format, using some very basic command-line parameters: https://gist.github.com/LinguList/7612513

This just gives an idea regarding the major arguments which one would like to cover (and later also to document):

https://gist.github.com/LinguList/7612513#arguments

**Comment by xrotwang** [comment]
Regarding the multitude of parameters: Ideally, the defaults would be sensible most of the time, but these could be overwritten by a local config file, e.g. one section per sub-command, one option per argument:
```
[sca-cognate-detection]
threshold = 0.7
method = upgma
```
This will already provide one layer of configurability. If then all options can be overridden by corresponding command line options, I guess that's all we need. I also think that there are smart ways of re-using documentation of the arguments of python functions for the hekp messages of the cli.

**Comment by LinguList** [comment]
> I also think that there are smart ways of re-using documentation of the arguments of python functions for the hekp messages of the cli.

I agree, many things are already fully described.

One problem that remains is the workflow steps we have in some analyses.
So cognate detection starts by loading the file first, thereby checking
it, then creating the scorer (when using lexstat proper), that is,
training it, and then applying the full analysis.

The people from the morfessor project
(http://morfessor.readthedocs.org/en/latest/) also have command lines in
python, but I do not know how they store their models in cash after
running one training analysis, but they basically also have to do it,
since the analyses may run for some time and it is time consuming to
wait if something breaks. But we'll probably best handles this with
intermediate textfiles that we write and that contain the data, so
that's more transparent.

**Comment by xrotwang** [comment]
I'd say the aspect of long-running analyses is one of the biggest motivators for UNIX-style pipelines, because it makes the non-interactive use case more accessible and interoperable. Basically we trade interactivity for advantages like being able to easily parallelize analyses, or send them off to other machines, or let them run over night, ...

**Comment by xrotwang** [comment]
Regarding morfessor: I think the [note here](http://morfessor.readthedocs.org/en/latest/filetypes.html#binary-model) says it all. Python pickles are a bad format to save state of intermediate steps during long running scientific analyses. Text based formats are preferable, I think. And if there's a lot of data, maybe sqlite3 files.

**Comment by LinguList** [comment]
I have given up the pickling idea now.
Before, this was mainly due to performance issues, but since you changed
the loading routines somehow, this is no longer an issue, and even files
with some 40 to 50 languages can be loaded after processing (I mean, the
scoring dictionaries, the files are large then in text form with some 10
MB or soemtimes more) without really feeling great performance problems.
So we could consider to say bye bye to the pickling routine for
wordlist-derivatives in general.

Instead, saving files along with their scorer in the expanded
LingPy-format has been shown to work well during my least application
studies. Although I know that not many people really like that format,
since it mixes CSV and other elements...
