### ISSUE TITLE
Error messages in multiple

### ISSUE THREAD

**Issue by cysouw** [lingpy/lingpy#177]
I tried to make an executable for "multiple". It works fine, but in some cases there are warnings ("There are empty segments in the consensus."), which also prints some information to the output (stdout). I think this information should not be printed to the output, but to the error message.

```
2015-11-01 22:32:36,524 [WARNING] There are empty segments in the consensus.
1 7 0 5 7
1 7 0 5 7
2015-11-01 22:32:36,525 [WARNING] There are empty segments in the consensus.
1 7 0 5
1 7 7 5
2015-11-01 22:32:36,526 [WARNING] There are empty segments in the consensus.
1 7 2 5
1 7 0 5 7
```

Try the following in the terminal: `cat tmp.txt | align.txt`

[tmp.txt](https://github.com/lingpy/lingpy/files/24946/tmp.txt)
[align.txt](https://github.com/lingpy/lingpy/files/24947/align.txt)

(sorry: the executable didn't want to upload here, so I had to rename it as "align.txt". The suffix is of no meaning  :-)

**Comment by LinguList** [comment]
This is a "wanted feature": we have a config file which allows you to adjust different kinds of "errors", and we distinguish "warnings" from errors. The point here is that at certain points in the alignment, the prosodic string contains unwanted zeros, since it always expects a segment, but since we are dealing with profiles, it can average to zero. So this is something that point to an alignment that doesn't go pretty well. i don't recall, how exactly one can switch off warnings, but I'll add it and I'll leave this issue open until we also have it in the documentation. A general review of this warning may also be in order, but know that it usually does not occur in alignments that "go well".

**Comment by cysouw** [comment]
got it!

- however: this is a "warning", but it sends output to stdout. That seems not right
- as for the problem: I think it is caused by specific unicode elements in the strings: do you have a description of which unicode elements are allowed?

**Comment by LinguList** [comment]
I can add a small and probably useful routine that shows which elements are recognized and which not. It's already there, but not transparent, since all elements which are not recognized as "IPA" are converted to an internal zero-character. I can add a flag that throws a warning already at this stage. As to the question with stdout and warnings, I think it is fine, and it's not stdout, if you pipe it, since it won't be written to file if you pipe the stuff as > text.txt, as far as I understand, but @xrotwang will probably have a more precise answer to that.

**Comment by cysouw** [comment]
@xrotwang : if you try the above pipe `cat tmp.txt | align > result.txt` then there are numbers written to file which belong to the warning, not to the real output. Could you have a look at that?

**Comment by xrotwang** [comment]
@cysouw will do. It's probably a matter of logging config.

**Comment by LinguList** [comment]
I just looked up the respective lines in multiple.py: https://github.com/lingpy/lingpy/blob/master/lingpy/align/multiple.py#L517-L520

There's an explicit print-statement tight to the log-level. So if you change your log.ini accordingly, it won't appear.

But we generally need more explicit warning if there are bad sounds in the data which are not (yet) recognized by LingPy, maybe a log-file containing the symbols tight to each word, as well as some documentation of the logging and further possibilities in the setup. 

In the meantime, you can patch the align.py script as follows (by tweaking the logger from inside the script)

```python
#!/usr/bin/env python3

# multialignment using lingpy


from lingpy import log
from lingpy import *
import sys

# modify the global lingpy logger
log._logger = log.logging.getLogger('lingpy')
log._logger.setLevel(log.logging.INFO+1)

with open(sys.argv[1]) if len(sys.argv) > 1 else sys.stdin as f:
    seqs = f.read().splitlines()

msa = Multiple(seqs)
msa.lib_align(gop = -5)
msa.iterate_orphans(0.5)

with sys.stdout as f:
    for string in msa.alm_matrix:
        f.write(" ".join(string)+'\n')

```

**Comment by xrotwang** [comment]
I think to make lingpy more pipeline-friendly, we should make sure, logging is sent to `sys.stderr` by default.

**Comment by xrotwang** [comment]
@LinguList I see three ways to fix this issue. Replace the `print` calls [here](https://github.com/lingpy/lingpy/blob/master/lingpy/align/multiple.py#L517-L520)

1. `log.info`: Would be preferable in terms of code consistency, but will prepend all the logging house-keeping info.
2. `log.<method>` with a custom LogLevel which is configured not to output any additional info.
3. `sys.stderr.write`.

I think I would lean to 1 and maybe 2, considering that there are more places like this in lingpy, where something is output to a console, which may be useful for copy&pasting as a block (where the added log-formatting would get in the way).

**Comment by LinguList** [comment]
Replacing the print-statements makes definitely sense to me, although it is useful for debugging purposes to have a nicely formatted string without the logging-stuff before, since it is otherwise very difficult to see what's going on, especially in alignments. But couldn't one in these cases simply adjust the format string to contain a newline for example? This would already be enough for me, when debugging the code. 

And in general, the warning thrown in the lines in multiple, could also be put to the debug level. It is not related to IPA recognizion, but more to the rationale behind multiple alignment including prosodic-profiles.

**Comment by xrotwang** [comment]
Maybe a variant of [this approach](http://stackoverflow.com/a/22937976) would be ideal.

**Comment by LinguList** [comment]
Yes, that seems to be a good solution!
