### ISSUE TITLE
Error in msa.lib_align

### ISSUE THREAD

**Issue by cysouw** [lingpy/lingpy#181]
I get the following error, which I cannot fix...

```
from lingpy import *
with open ('test.txt') as f:
    seqs = f.read().splitlines()
msa = Multiple(seqs)
msa.lib_align(gop = -5)
```

error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/lingpy-2.4.2-py3.5.egg/lingpy/align/multiple.py", line 975, in lib_align
    run[0], run[1], run[2], kw['factor'], kw['restricted_chars'])
  File "/usr/local/lib/python3.5/site-packages/lingpy-2.4.2-py3.5.egg/lingpy/align/multiple.py", line 332, in _get_pairwise_alignments
    mode)
  File "/usr/local/lib/python3.5/site-packages/lingpy-2.4.2-py3.5.egg/lingpy/algorithm/cython/_calign.py", line 1188, in align_pairwise
    dist = 1 - ( 2 * sim / ( simA + simB ) )
ZeroDivisionError: float division by zero
```

[test.txt](https://github.com/lingpy/lingpy/files/32631/test.txt)

**Comment by LinguList** [comment]
You are aligning elements which are not recognized by lingpy.
The default treatment is to tolerate these elements and to convert them
internally to a 0 (zero) which does not score with any other character.

if all of your characters are zero internally, there's nothing to align.

Just switch the chars to lowercase, and they will be recognized as IPA
and converted to sound classes.

If you want to avoid the conversion itself, there's a tweak, but I can't
look it up right now.

**Comment by cysouw** [comment]
Now I am again confused (I though I got it...)

I explicitly converted my data to SCA, because I though you would use SCA. But you don't allow SCA as input? Why not? If you convert them internally anyway into SCA then it should be possible to enter SCA data directly, I though... But I am probably missing something.

(BTW: in your book on p. 124 on SCA it says that IPA [u] belong to the class Y "rounded front vowels". Either [u] should go with O "rounded back vowels", or you should rename those classes :-).

**Comment by LinguList** [comment]
Well, the function you use was created to align things in IPA. It was not created to guess that things are eitehr IPA or SCA or whatever. The class is a wrapper for alignment analyses that uses rather advanced steps for the alignment process.

You can tweak it and pass your own sound classes to it, as well as your own scoring function, and your own sonority profiles.

To use your classes, you can try it as follows:

```python

from lingpy import *
with open ('test.txt') as f:
    seqs = f.read().splitlines()
msa = Multiple(seqs)
msa.lib_align(gop = -5, classes=seqs)
```
This should do the trick. The multi-tiered representation remains though. But this was the initial design principle of the Multiple-class.

And reg. the vowels, you are right: the words should be open and close rather than back and front.

**Comment by cysouw** [comment]
OK. got it
