### ISSUE TITLE
algorithm/cython/misc.pyx matrix set bug

### ISSUE THREAD

**Issue by StephenEhmann** [lingpy/lingpy#183]
this code will result in only values on the diagonal begin set. it seems like an obvious bug, seems like it is not intended. but I am wondering how things have been working properly in the presence of this bug...
    def __setitem__(
            self,
            tuple x,
            float y
            ):
        cdef int i,j
        i = self.chars2int[x[0]]
        j = self.chars2int[x[1]]

        if i == j:
            self.matrix[i][j] = y
            self.matrix[j][i] = y
        else:
            self.matrix[i][i] = y

**Comment by LinguList** [comment]
The reason is simple: The code was never used in this way: the setitem-method is only theoretically usable, but upon init, it doesn't occur. It is even not specified, what the function is supposed to do. I have to admit that I completely forgot what I wanted to do with this. 

I guess the == needs to be changed to !=, but I should generally look into this and see whether a setitem method is needed after all...

**Comment by LinguList** [comment]
okay, fixed with last PR
