### ISSUE TITLE
Add `pip install lingpy` as an alternative installation method

### ISSUE THREAD

**Issue by pavelsof** [lingpy/lingpy#193]
The README instructs users to clone the repo and run the setup script, and this works fine (by the way, it would be helpful to mention that the repo could be safely disposed of afterwards). However, it would be nice if lingpy could be installed using pip as well.

Currently the default version of lingpy on PyPI is 2.0, and the installation fails (the distribute_setup script raises an error). There is also the 2.4.1-alpha-pre-release version, which installs perfectly fine. In other words, this works:
```
$ pip install lingpy==2.4.1-alpha-pre-release
```
while this fails:
```
$ pip install lingpy
```

I played with the repo a little bit, and it seems that the problem is specific to 2.0. Checking out any of the tags `v2.2`, `v2.3`, and `2.3` and telling pip to install that works (of course, checking out `v2.0` and telling pip to install that fails with the same distribute_setup error).

Thus, uploading any non-alpha, >2.0, version on PyPI will automatically fix the issue and make the library pip-installable again.

Thank you for developing lingpy :)

Kind regards,
Pavel

**Comment by LinguList** [comment]
Thanks for notifying, and you're perfectly right in your suggestion!
We'll leave this issue open until the next official release of
LingPy-2.4 (or we might better call it 2.5, since 2.4 was now used too
often in all kind of development versions).

By then, we'll adjust the README.md but also upload a new
pip-installable version to LingPy.

thanks again for bringing this up. We need this kind of input!

**Comment by pavelsof** [comment]
I am happy that it was helpful :)
