### ISSUE TITLE
Provide qlc2cldf conversion

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#225]
To prepare switch from qlc to cldf (i.e. switching from one NEXUS-style data file to data packages, either multifile directories or zip archives), we need a qlc2cldf conversion tool.

**Comment by LinguList** [comment]
Should I go ahead with an example here, which contains as much as all that I have to offer regarding complexity at the moment, that is, scoring dictionaries, alignments, partial cognates, trees, etc.?

**Comment by xrotwang** [comment]
Yes, an example to work from would be good. Somewhat related: I'm working on template-based output of alignments, and was having difficulties forcing alignment output with the `confidence` argument set to `True`. The test data file `KSL3.qlc` seemed to contain a scorer, which is required for calling `get_confidence`. But then I got `KeyError`s - so it may be the wrong scorer?

**Comment by LinguList** [comment]
Yes, the "confidence" stuff requires some specific scorer that needs to be passed to the function. I'll quickly have a look into it and provide an example.

**Comment by LinguList** [comment]
Allright, I just remembered and checked it. The confidence stuff needs a scorer. Alignmetns, hwoever, does not expect a scorer and therefore doesn't read it, so one needs to load both a lexstat and an alignment class:

```python
>>> lex = LexStat("KSL3.qlc")
>>> alm = Alignments("KSL3.qlc") # or also alm = Alignments(lex)
>>> alm.get_confidence(lex.scorer, 'cogid') # default for kw "ref" is "lexstatid"
```

It seems that if we go for the datapackage version, it might be useful to allow already the Wordlist class to read in a scorer, if this is supplied in the datapackage?

**Comment by LinguList** [comment]
Additional information regarding the workflow problems here:

* one can make alignments without a scorer
* for the confidence, however, one definitely needs a scorer
* this needs to be passed from outside

Furthermore, it cannot be any scorer, but it needs to be a scorer that is tight to the "numbers" in a LexStat object, where every IPA-string is referenced with its sound class, it's language ID and it's prosodic string. Since these scorers are automatically only produced by LexStat (one needs a wordlist to produce them anyway), we have this strange workflow. But I was never happy with it, although I think it makes sense to separate alignments from cognate detection in the classes Alignments and LexStat.

**Comment by LinguList** [comment]
Sorry, I just realized this was crap: alignmetns and wordlist also read scorers, but they do not create the wordlist.bscorer argument, but a general scorer argument instead which is a dictionary that holds severals scoreres. So 

```python
alm.get_confidence(alm.scorer['rscorer'], 'cogid')
```
works.

**Comment by LinguList** [comment]
I just wrote a first quick example for a function that converts a wordlist to a zip-file with csv, and the other stuff all separated:

[qlc2cldf.zip](https://github.com/lingpy/lingpy/files/180121/qlc2cldf.zip)
