### ISSUE TITLE
SyntaxError: Non-ASCII character '\xcb' in file C:\cog\lingpy-2.0\lingpy\settings.py on line 84, but no encoding declare

### ISSUE THREAD

**Issue by StephenEhmann** [lingpy/lingpy#229]
On Windows 7 I get an error due to the file having a utf-8 char but it does not have the proper header.  Maybe this is not an issue on Linux so it hasn't been seen yet?

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import lingpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\cog\lingpy-2.0\lingpy\__init__.py", line 31, in <module>
    from .settings import *
  File "C:\cog\lingpy-2.0\lingpy\settings.py", line 84
SyntaxError: Non-ASCII character '\xcb' in file C:\cog\lingpy-2.0\lingpy\settings.py on line 84, but no encoding declare
d; see http://python.org/dev/peps/pep-0263/ for details
>>>

**Comment by LinguList** [comment]
I think it's because you use the old 2.0 version. We head for a new
release in the second half of the year, but the current version at
GitHub, that is, the current state as is, should be stable enough and
not report this error. So best download the version 2.4.dev which is the
current master on GIT, and manually install LingPy as in the
instructions. Let me know if the error still persists, if now, we can
close this issue.

I hope we have the new version online soon, but it will still take some
time. Potentially, we will file an intermediary release to update PyPi,
so that the code runs normally on all platforms...

**Comment by StephenEhmann** [comment]
thanks for the fast response.
Suggestion: documentation refers to https://pypi.python.org/pypi/lingpy/2.0, change it to refer to https://pypi.python.org/pypi/lingpy
Suggestion: https://pypi.python.org/pypi/lingpy should have 2 links: a) latest stable release (2.3) and newest (2.4 alpha)

I ran pip install on lingpy and I got the below...
I am wondering what lingpy2 is?  Is that the new package name?

c:\>pip install lingpy
Collecting lingpy
  Downloading lingpy-2.0.tar.gz (8.4MB)
    100% |################################| 8.4MB 152kB/s
  Running setup.py (path:c:\users\stephen\appdata\local\temp\pip-build-a7enlz\lingpy\setup.py) egg_info for package ling
py produced metadata for project name lingpy2. Fix your #egg=lingpy fragments.
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\python27\lib\site-packages (from lingpy2)
Requirement already satisfied (use --upgrade to upgrade): networkx in c:\python27\lib\site-packages (from lingpy2)
Requirement already satisfied (use --upgrade to upgrade): regex in c:\python27\lib\site-packages (from lingpy2)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python27\lib\site-packages (from networ
kx->lingpy2)
Installing collected packages: lingpy2
  Running setup.py install for lingpy2 ... done
Successfully installed lingpy2-2.0

**Comment by LinguList** [comment]
No, you need to download the current github source. With pip, you still
get the one on PyPi that doesn't work (there's an issue filed on this,
also to be solved with the new release). You can see this from the
version lingpy2-2.0.

Otherwise it won't work. We'll update documentation immediately in case
we decide for an intermediate release before the major release.

In the meantime, please just use the stable github-version, and we try
to handle things as soon as possible (which may take some time, but it's
unfortunately inevitable with our restricted circle of two people
working on LingPy in their free time...).

**Comment by StephenEhmann** [comment]
function = lambda idxA,*idxy*: calign.align_pair(
the idxy in this code in lexstat.py should be idxB, the code happens to
work because idxB is defined as the local variable when this lambda is
called....

**Comment by LinguList** [comment]
Thanks for notifying a potential bug. Could you  please give me the line
and teh script you're referring to, otherwise, I can't track the error.

**Comment by LinguList** [comment]
I just grepped all files, there is no line in which the line you
mentioned occurs. Are you by any chance referring to older versions?

**Comment by StephenEhmann** [comment]
I downloaded 2.4.1a0 today and it is in lexstat.py line 1178

**Comment by LinguList** [comment]
please download the current github code:

* https://github.com/lingpy/lingpy/archive/master.zip

You'll see, Version 2.4.1 alpha etc. are OLD, as I said above, and we're going to make a new release v3.0 in the end of the year and potentially a release before to have it savely on PIP. Current lingpy doesn't have the issue anymore, so for a version that is much more advanced and regularly works cross-platform, just use the current development code.

**Comment by StephenEhmann** [comment]
thanks for clarifying, I will follow those instructions, I didn't realize
that it was different than the download link....
