### ISSUE TITLE
ASJP to Dolgo string

### ISSUE THREAD

**Issue by PhyloStar** [lingpy/lingpy#230]
I am trying out conversion from ASJP to Dolgo format. I mean the original ASJP format. The code looks as follows:

>>> from lingpy import *
>>> rc(schema="asjp")
>>> tokenized_str = ipa2tokens("ia7ita")
>>> tokens2class(tokenized_str,"sca")
[u'I', u'A', u'H', u'I', u'T', u'A']
>>> tokens2class(tokenized_str,"dolgo")
[u'V', u'V', u'0', u'V', u'T', u'V']
>>> prosodic_string(tokenized_str)
u'XYBYBZ'

The dolgo conversion for "7" is coming out as "0" but the SCA conversion is right. I also observed the same issue with the following ASJP characters:
Z
5
N

**Comment by LinguList** [comment]
@PhyloStar suggested these changes:

> The modifications for dolgo_el might look like:
> S : s, z, S, z --> S : s, z, S, z, Z
> N : n, 8, N --> N : n, N, 5
> H : H, h --> H : H, h, 7 

4 is also missing, so Dolgo now should be:
```text
V : a, e, i, o, u, E, 3
K : k, g, x, X, C, c, q, j
P : p, b, f, v
H : H, h, 7
J : y
M : m
N : n, 5, N, 4
S : s, z, S, Z
R : r, l, R, L
T : t, d, 8
W : w
+ : +
1 : 1
_ : _
```

And ASJP-model (aka brown-model) also needs to be modified.

In general, it will be useful to provide some "ASJP simple model" which converts IPA directly to ASJP, so that these confusions stop. Would be straightforward by modifying the current asjp model slightly. This would then fit into a larger Milestone in which

* the schema (asjp and ipa) is refined, with renamed models to avoid confusion (brown, etc.)
* a custom function to convert IPA to asjp is offered, so that sound class conversion is no longer wrongly used for the purpose of converting ipa to asjp (sound classes are not identical with alphabets)

@PhyloStar. For the moment, just replace the old DOLGO with the one above, but make sure to find your local directory ".cache/lingpy/" and delete all files which are in there, to make sure the cache is emptied and you can use the new functions!

I'll try and submit a PR solving the issues by end of week.

**Comment by LinguList** [comment]
this should be solved with the most recent PR, @PhyloStar , could you please check again, whether it works, in case you use the code? We should probably also think of adding explicit tests (yet theres so much to do...)
