### ISSUE TITLE
igraph requirement

### ISSUE THREAD

**Issue by evoling** [lingpy/lingpy#254]
When you run `from lingpy import *` from a fresh install you get the warnings:

```
2016-06-06 16:36:51,060 [WARNING] Module 'sklearn' could not be loaded. Some methods may not work properly.
2016-06-06 16:36:51,060 [WARNING] Module 'igraph' could not be loaded. Some methods may not work properly.
```

`pip install igraph` installs the wrong igraph library, and causes cryptic errors when you try to import lingpy. You need `pip install python-igraph` instead.

**Comment by LinguList** [comment]
***, I know this issue with igraph, since I always have this igraph problem when running python on another computer. Thanks for notifying! Question is, how we should handle this: should we post this on the installation instructions in the documentation, that igraph is python-igraph, or should we add it to pip-requirements. The problem is, we explicitly exclude igraph from the default requirements, since it may be difficult to install it on other machines (like Windows). The warning is also important in case users try and use igraph-related stuff but we never wanted it to show up when you import "*". 

I'll have to look into the import statements to fix this. I think we should probably only throw the warning or an explicit errors in case users really try to use the forbidden methods.

**Comment by evoling** [comment]
It should be noted in the documentation. The problem should go away eventually, since the "other igraph" has been renamed "jgraph". Maybe you could make an "extra-requirements.txt" file for things you don't want to include by default (requirements files can have comments I think, so you could have a line explaining what each bit is needed for). The other thing would be to customise the warning message, or make a new warning message if it finds the wrong igraph.
