### ISSUE TITLE
.tokenize method in workflow.py

### ISSUE THREAD

**Issue by bundessarah** [lingpy/lingpy#255]
Hi there, when I'm trying to run your workflow.py file from the tutorial (lingpy/doc/source/tutorial/examples/, but also found as an example on your website), I always stumble over the step that prompts me to use the `tokenize` method on a wordlist object:

````
from lingpy import *

# load a wordlist object
print("[i] Loading the wordlist.")
wl = Wordlist('DOGON.qlc')

# tokenize the data using the ortho-profile Heath2012.prf
print("[i] Tokenizing the wordlist.")
wl.tokenize('Heath2013.prf',column='IPA')`
```
This throws an AttributeError, saying that the object has no such method. I've searched the whole library for it, and it's never defined, so it doesn't turn up with `dir()` either. Have you changed the method name? The `ipa2tokens` method doesn't seem to do exactly the same, even though with it, the tokenizer probably wouldn't be so hard to implement manually. I'm a Python newbie, so I'm just wondering if I've missed something.

And if I haven't - could you point me in the right direction in the docu as to how I can create a similar workflow with comparable results? Thank you!

**Comment by LinguList** [comment]
This should not happen with our new tutorial at lingpy.org. There, the tonenize function was discarded, since its now no longer used. Can you please confirm that you talk about the current tutorial at http://lingpy.org/workflow.html ?

-------- Ursprüngliche Nachricht --------
Von: bundessarah <notifications@github.com> 
Datum:06.06.2016  19:24  (GMT+01:00) 
An: lingpy/lingpy <lingpy@noreply.github.com> 
Betreff: [lingpy/lingpy] .tokenize method in workflow.py (#255) 

Hi there, when I'm trying to run your workflow.py file from the tutorial (lingpy/doc/source/tutorial/examples/, but also found as an example on your website), I always stumble over the step that prompts me to use the tokenize method on a wordlist object:

from lingpy import *

# load a wordlist object
print("[i] Loading the wordlist.")
wl = Wordlist('DOGON.qlc')

# tokenize the data using the ortho-profile Heath2012.prf
print("[i] Tokenizing the wordlist.")
wl.tokenize('Heath2013.prf',column='IPA')`
This throws an AttributeError, saying that the object has no such method. I've searched the whole library for it, and it's never defined, so it doesn't turn up with dir() either. Have you changed the method name? The ipa2tokens method doesn't seem to do exactly the same, even though with it, the tokenizer probably wouldn't be so hard to implement manually. I'm a Python newbie, so I'm just wondering if I've missed something.

And if I haven't - could you point me in the right direction in the docu as to how I can create a similar workflow with comparable results? Thank you!

**Comment by LinguList** [comment]
I now adjusted the stuff also in the workflow.py file (but you need to download from github). I didn't test it, but it should work, yet in future versions of LingPy we'll put this workflow.py file to some other repo, like lingpy/cookbook on github, for example, since this may make it more transparent.

On the website, I confirmed, there is no further example pointing to the workflow.py, so this should be fine.

What you, @bundessarah, need to know in this context is just that the wordlist.tokenize method is no longer primary part of lingpy, but a library itself, accessible at lingpy/tokenize, at the moment, but it may well change its name, if I understand @bambooforest's (the author of the library) idea correctly. 

But as long as you have some okayish IPA in your data, you should be fine with simply following the current workflows.

**Comment by bundessarah** [comment]
Thank you for the quick reply, it works on the test data now!

**Comment by LinguList** [comment]
cool, that's always a relief if things work well on other people's
machines...

**Comment by bundessarah** [comment]
to be honest, I haven't quite figured out how to format my own data so that the LexStat function likes it, but that's probably a result of either my lack of Python proficiency or my Windows version (or a combination thereof) :) I'm very thankful for this powerful library, though, so I won't give up!

**Comment by LinguList** [comment]
I can't promise to solve problems immediately, but you could either send
me your data via email, or paste a little part of it (which you wish to
share), and we'll figure out how it goes (may just take some time for me
to answer on this...)
