### ISSUE TITLE
LexStat defines useful functions in a private object method

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#308]
This LexStat method defines some functions which are more general. 
https://github.com/lingpy/lingpy/blob/0432b7b845064223dcbb6be4e31430ed5d752fb1/lingpy/compare/lexstat.py#L571

In particular, none of these functions use any instance or class attributes of `LexStat`, so it would make sense to define them on the module level.

**Comment by LinguList** [comment]
more examples? If we go for this, we should have them all. In the
meantime, I am inclined to make some things which were external
class-based, for example, you can now type:
```
>>> wl.iter_rows('concept', 'doculect', 'ipa')
```
but before you had to write:
```
>>> iter_rows(wl, 'concept', 'doculect', 'ipa')
```
Having a list of wishes would be useful to address these things in a
run. Although, apart from that the funciton you mention doesn't need to
be assigned to LexStat, I don't see where it would be used otherwise...

**Comment by LinguList** [comment]
I just decided to drop this: we could put it outside, but hte cluster methods are by no way useful for any class outside this, as they are available as standalones in the cluster package. For me it is less confusing if I have my methods important for the class inside the class. Unless we have a list where these things could be re-used by other code blocks, it is not really relevant for now. Please re-open if more examples can be found, or make a PR.
