### ISSUE TITLE
Unknown tokens error when creating LexStat object (ASJP)

### ISSUE THREAD

**Issue by pdekker12** [lingpy/lingpy#368]
When I create a LexStat object (model="asjp") for the NorthEuraLex dataset, I get an error saying that some word forms consist of only unknown tokens. Before, I did not experience this error.

```
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/basic/parser.py", line 364, in _apply
    res = function(s, *args, **kwargs)
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/compare/lexstat.py", line 332, in <lambda>
    cldf=self._cldf)])
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/sequence/sound_classes.py", line 783, in tokens2class
    raise ValueError("[!] your sequence contains only unknown characters")
ValueError: [!] your sequence contains only unknown characters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipeline.py", line 618, in <module>
    main()
  File "pipeline.py", line 352, in main
    cd.cognate_detection_lexstat(tsv_path_train, tsv_cognates_path_train, input_type=FLAGS.input_type)
  File "/home/peter/git/wordprediction2/cd.py", line 357, in cognate_detection_lexstat
    lex = LexStat(tsv_path + ".tsv", model=model)
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/compare/lexstat.py", line 330, in __init__
    lambda x: [int(i) for i in tokens2class(
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/basic/wordlist.py", line 127, in add_entries
    self._add_entries(entry, source, function, override, **keywords)
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/basic/parser.py", line 427, in _add_entries
    _apply(key, self[key][idx], **keywords)
  File "/home/peter/.local/lib/python3.6/site-packages/lingpy/basic/parser.py", line 366, in _apply
    raise ValueError('Could not convert item ID: {0}.'.format(key))
ValueError: Could not convert item ID: 2425.
```

The input file is a TSV file with the following structure:
```
ID	DOCULECT	CONCEPT	COUNTERPART	IPA	TOKENS	COGNATES_IELEX	CONCEPT_COGNATES_IELEX
0	fin	Abend::N	ilta	ilto	i l t o		
1	krl	Abend::N	ilta	ilto	i l t o		
```

Errors where given for the following words:
```
1758	ady	alt::A	жъы	Z3	Z 3		
1887	ady	alt[Lebewesen]::A	жъы	Z3	Z 3		
1892	dar	alt[Lebewesen]::A	бухъна	buqna	b u q n a		
1982	niv	Alter::N	ань	EN	E N		
2001	lez	Alter::N	яш	ES	E S		
2425	bre	ändern::V	cheñch	SES	S E S		
```
The errors seem to be given mostly on short words that only consist of the tokens E, S, Z and 3. I do not understand why this happens, I thought these should be valid ASJP tokens

**Comment by LinguList** [comment]
This behavior is wnated to warn users of over-using bad characters in lingpy. Ideally, you should check all conversions of IPA chars to sound class chars, we now refuse to align words where no char is known internally. 

Your problem is deeper, though, as you assume that "model=asjp" means that lingpy expects asjp letters. But this is contra any documentation, as it only means that asjp is used INTERNALLY as sound class. To account for a conversion from asjp external instead of IPA, you need to change the "schema":

```
>>> from lingpy import *
>>> rc(schema="asjp")
```

you need to do this prior to any computation.

See [here](http://lingpy.org/reference/lingpy.html#module-lingpy.settings) for the "schema". Even more precisely [here](http://lingpy.org/docu/data/data.html?highlight=schema) (part of the standard documentation of lingpy).

Please check also our tutorial, now accepted for journal of language evolution: [pdf here](http://lingulist.de/documents/papers/list-et-al-2018-lingpy-tutorial.pdf) and tutorial via [lingpy/lingpy-tutorial](https://github.com/lingpy/lingpy-tutorial).

**Comment by pdekker12** [comment]
Thanks for the clarification! I probably did not study the docs close enough. I remember that in the past, changing  model=SCA to model=ASJP made LexStat recognize the ASJP characters, which made me believe this option also represented the input alphabet.

**Comment by LinguList** [comment]
not really possible: lingpy always assumes that input chars is IPA, only forcing via model works, and SINCE it was silently passing errors and producing problematic cognates, it could go unrecognized, which is now prevented with the new sanity checks... But glad having confirmation that this was a useful addon. Better more errors explicitly than silent erroors that lead to wrong computations...
