### ISSUE TITLE
Collect new round of non-standard "IPA" letters to add them at once

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#374]
At some point, I was apparently loading a word list with `ɼ` (obsolete variant of `r̝`) into LingPy and trying to convert it into Dolgopolsky sound classes.

I have looked through my files to see what that might have been about and found nothing, so it barely matters, but is there any scope use in expanding sound classes to include letters like that at all?

**Comment by LinguList** [comment]
Yes, sure, we regularly do that in PRs. And there are other letters it doesn't accept. It's some work, though, as you have to add the character to all five sound class models:

* dolgo
* sca
* asjp
* cv
* art

Otherwise, you'll fail the test. In this way we make sure that asjp and sca, etc. always express the same sounds. I welcome any PR that adds so far unrecognized characters. And you should be careful when using too many bad chars in your data, as it will some time most certainly fail, and debugging these cases is annoying (always load lexstat with "check=True", I recommend).

**Comment by LinguList** [comment]
We found another ugly letter recently: ʯ  (thought, lingpy would know all of them by now). 

So we have now:

* ɼ
* ʯ

Let's collect them here in this thread (just copy my list and add new ones), so we can do this at once, when preparing next release of lingpy.

**Comment by LinguList** [comment]
Yes, I know, but we already included a lot from there, plus a bunch of "lookalikes" from the unicode project. I guess, the future of this will be our "multicode" idea, where we systematically collect the lookalikes and correct them (although people may not like this in lingpy context): imagine we use this before segmenting in lingpy, or when converting to sound classes, it might increase tolerance against the stupid characters that occur once in one dataset and force lingpy to strike.
