### ISSUE TITLE
`Wordlist.from_cldf` should offer standard lingpy names

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#398]
Currently, if one wants to make a full-fledged analysis with LingPy from cldf-data, there may be a couple of bugs, often due to the fact that although lingpy officially is "flexible" as to the names for "concept" and "doculect", it is not internally. While these need to be addressed, we should default in cldf conversion to the standard names "doculect" and "concept" when importing cldf-data in lingpy. The same should hold for cognate sets. Thus, the import should replace the following commands we have to use now and make them superfluous:

```
from lexibank_lieberherrkhobwa import Dataset as DS

wl = Wordlist.from_cldf(DS.cldf.joinpath('cldf-metadata.json'), col='language_id', row='parameter_id')
wl.add_entries('cogid', 'cogid_id', lambda x: x)
wl.add_entries('doculect', 'language_id', lambda x: x) # or language_name (!?)
wl.add_entries('concept', 'parameter_id', lambda x: x) # or parameter_name (!?)
wl = Wordlist(wl)
```

**Comment by Anaphory** [comment]
Is this a thing that coult/should be provided by the existing 'alias' infrastructure, or would that be bad?

**Comment by Anaphory** [comment]
Well, yes, I'm with @xrotwang that there are good reasons to deprecate and get rid of the alias system, replacing it by something more explicit and controllable. However, until that is a thing, I see this as one of the reasonable use cases for using aliases. I would not add another obscure default, but instead make the `.from_cldf` method take parameters that explicitly construct those aliases.

I can imagine that parameter to take a dictionary of mappings that should be applied (`{'Lect_ID': 'doculect'}`), with the special, default value `None` for the default mappings (`{'Language_ID': 'doculect', 'Parameter_ID': 'concept', ...}`), so that the empty dictionary `{}` can be used to force 'do not add any new aliases'.

**Comment by xrotwang** [comment]
I agree with @Anaphory that using aliases in this case is reasonable - as long as all of this happens in this one method (and preferably at the start of it). As soon as classes inheriting from `Wordlist` overwrite `from_cldf` this will become ugly, though. I'm almost tempted to recommend turning `from_cldf` into a function for this reason.

**Comment by LinguList** [comment]
Okay, but what I would actually like to understand here is, what the reason was for your selection of the headers, @Anaphory? This is not really obvious: are these CLDF names? And obviously, the "cognacy" should not be aliased with "cogid", as it is a string, or could be a string, while "cogid" should rather be produced as an integer > 0 key via `Wordlist.renumber('cognacy', cogid')`. 

Ah, sorry, just understood: if I can pass an "alias" thing to the `from_cldf`, this is what you suggest, right? Because the other use would be to provide a new [`wordlist.rc`](https://github.com/lingpy/lingpy/blob/master/lingpy/data/conf/wordlist.rc) for the specific case of cldf. And this may lead to problems, I guess.

**Comment by Anaphory** [comment]
> Ah, sorry, just understood: if I can pass an "alias" thing to the `from_cldf`, this is what you suggest, right?

Yes, I am essentially saying that your code above should become

    wl = Wordlist.from_cldf(
        DS.cldf.joinpath('cldf-metadata.json'), col='doculect', row='concept',
        alias={'Cogid_ID': 'cogid', 'Language_ID': 'doculect', 'Parameter_ID': 'concept'})

I'm not sure I follow @xrotwang's points just yet. It might require looking at possible default alias sets and use cases for overloading `.from_cldf()`, which I'm not in a state to do right now.

**Comment by LinguList** [comment]
Okay. So no wordlist.rc, but aliasing, now I feel like I understand what you mean.

**Comment by xrotwang** [comment]
I'm fine with this solution. All I wanted to say above was that the perils of the alias system have been multiplied by the deep inheritance tree of `Wordlist` derivatives. So if we accept the alias system as solution here, we should make sure there won't be a proliferation of `from_cldf` methods. I'd basically like to declare the one `from_cldf` method [final](https://www.geeksforgeeks.org/final-keyword-java/).

**Comment by Anaphory** [comment]
Something like:
```
def cldf_aliases(dataset):
    corresponding = {
        'languageReference': 'doculect',
        'parameterReference': 'concept',
        # More well-defined and useful aliases go here
    }
    aliases = {}
    for cldf, lingpy in corresponding.items():
        try:
            aliases[dataset['FormTable', cldf].name] = lingpy
        except KeyError:
            pass
    return aliases
```

I think 'final' `from_cldf` sounds good, for convolutedly-similar reasons why I turned it into a `@classmethod` in the first place.

**Comment by LinguList** [comment]
Okay, and I would propose (I have done this in the past already), that we make a table of mappings between lingpy and cldf. As quite a few things can be seen as equivalent, but we have internally a different namespace which we do not really want to give up, or at least which I want to keep.

**Comment by tresoldi** [comment]
One thing I am probably missing from the whole discussion, but left wondering while working with `Wordlist.from_cldf()` this week: would it be better to "forget" about CLDF in the super `Wordlist` class, and have a `CLDFWordlist` (or whatever) inherited class?

Instead of forcing `Wordlist` to accept CLDF when necessary, we would create an interface to CLDF, just that. The `from_cldf()` method could become a part of this class `init` (or be called by it), and either the remapping could take place automatically or we could override methods adjusting the parameters before calling the super methods in a true oop-style, including stuff like `col=` and `cldf=True`. No need to consider the implications of CLDF when other classes inherit `Wordlist`, either you inherit from CLDF if necessary, or you abstract away from it.

Granted, I had no real experience with CLDF in a Wordlist, but I was not comfortable having to check at each time or remember if I was dealing with a CLDF dataset or not by keeping track of column names etc.

**Comment by Anaphory** [comment]
> Instead of forcing `Wordlist` to accept CLDF when necessary, we would create an interface to CLDF, just that. The `from_cldf()` method could become a part of this class `init` (or be called by it), and either the remapping could take place automatically or we could override methods adjusting the parameters before calling the super methods in a true oop-style, including stuff like `col=` and `cldf=True`. No need to consider the implications of CLDF when other classes inherit `Wordlist`, either you inherit from CLDF if necessary, or you abstract away from it.

Oof, that sounds bad. I often want to create a `Partial` or a `LexStat` from a CLDF wordlist, that's why this is a classmethod. Maintaining that option would mean to create a mixin class – and that would be very similar, but more complex than the current approach. Overwriting method behaviour sounds very intransparent and a recipe for hard-to-notice bugs, better clean up the existing methods to actually provide the flexibility LingPy promises, or remove the promise of that flexibility.

I would not consider CLDF semantically very different from a LingPy tsv file, it's just a different standard of writing to file, so an importer is the right thing for me. (Modulo the different related tables; but that's something that LingPy's data model cannot deal with, so should be left outside this discussion anyway.)

If LingPy wants to support different column headers there's nothing CLDF-specific about your problem and any functionality should be adapted to support that; if LingPy wants to deprecate support for different column headers, the importer needs to take care of that by doing the translation, and throw a warning/exception when it cannot.

**Comment by Anaphory** [comment]
> (I have done this in the past already)

So have I, to some extent; putting this in a transparent place in LingPy would be useful independent of where this discussion leads.

**Comment by LinguList** [comment]
Yes, right, @Anaphory, we'd need even in the tutorial at lingpy.org, some place where we say: these are lingpy's namespaces, and this is what they map to in cldf. We gradually already changed behavior in alignments, etc., for allowing to specify one column that keeps the tokens. At some places, "concept" is the only column that lingpy accepts, which is bad, as concept should always be "Wordlist.col". Cogid and cogids is maybe what causes most problems, as these differ from what cldf could deliver. 

If we had those cases fixed, where "concept" has a meaning, and it is not "row" what is asked for, plus a strategy for cognate identifiers, this would already be a great deal in compatibility. These problems are up to current lingpy code.

BTW: we also should normalize export to cldf. Currently, we don't have Wordlist.write_cldf.

**Comment by xrotwang** [comment]
@tresoldi: I'm with @Anaphory here. Subclassing `Wordlist` would make the whole inheritance tree even more complex, and mixins would make it even more intransparent. I still hope that there may be a LingPy 3 at some point, where the roles will be reversed: "LingPy tsv" will be just one output/input format, while the internal nomenclature will be based on CLDF terms.

So I'd see the current state as an infortunate transition, sort of like py2+3 with one codebase, where `from __future__ import`s and `from six import`s are littered all over the place and make it difficult to develop and stick with good longterm idioms.

**Comment by tresoldi** [comment]
OK, I see your points, you are right. Having a CLDF inheriting class would make things more complex with current organization. In a way this is related to something I briefly discussed with @LinguList this week about making the algorithms more independent, which likely stems from my general skepticism with object-oriented programming, feeling more comfortable with functional style myself.

I'll trust the other programmers here. :wink:

**Comment by LinguList** [comment]
Well, object-oriented is for me the most readable code, and it is still proving useful. Even [poepy](https://github.com/lingpy/poepy/) is based on a Wordlist class. I generally trust @xrotwang's pragmatism here: use classes, where they make sense, avoid them, where they don't (if I understand this correctly).

With our big grand plan of linpy3, many things can change here, but the general problem we face is: there are so many new ideas, that investing the time to start from zero seems like impossible, if we want to go on, although I am aware of the particular problems caused by decisions made in the past.

**Comment by tresoldi** [comment]
Not really advocating against, especially because changing (even if there were guarantees that the new setup would be better) would not only involve a lot of work, as you say, but nobody would really care -- there wouldn't be even a paper for saying "look, we spent one year on this".But let's discuss this, if at all, in the future, I shouldn't be hijacking this very specific issue.Il 31 gen 2019 21:52, Johann-Mattis List <notifications@github.com> ha scritto:Well, object-oriented is for me the most readable code, and it is still proving useful. Even poepy is based on a Wordlist class. I generally trust @xrotwang's pragmatism here: use classes, where they make sense, avoid them, where they don't (if I understand this correctly).
With our big grand plan of linpy3, many things can change here, but the general problem we face is: there are so many new ideas, that investing the time to start from zero seems like impossible, if we want to go on, although I am aware of the particular problems caused by decisions made in the past.

**Comment by Anaphory** [comment]
> BTW: we also should normalize export to cldf. Currently, we don't have Wordlist.write_cldf.

I know. You know [my current simple workaround for that](https://github.com/Anaphory/matrix_to_beastling/blob/master/Generic-LingPy-Wordlist-metadata.json), and because that is so simple, I think we should fix the import and the internals first, and not haste the export.

**Comment by Anaphory** [comment]
I just checked the code: Currently, `from_cldf` does not pass any CLDF semantic on to LingPy, anything that might work works by accident or explicit postprocessing. Making `languageReference` the `col` of the wordlist would actually be a different matter from making `languageReference` an alias of `doculect`, such that `col`, which defaults to `doculect`, would find `languageReference`.

Both of these sound complex in different ways, I don't know what would be better.

**Comment by tresoldi** [comment]
This week we ended up with a 
```
wl = Wordlist.from_cldf(DS.dir.joinpath('cldf', 'cldf-metadata.json'), col='language_id', row='parameter_id')
wl.add_entries('cogid', 'cognacy', lambda x: int(x))
wl.add_entries('doculect', 'language_id', lambda x: x)
wl.add_entries('concept', 'parameter_id', lambda x: x)
```

Good enough for prototyping and easy to understand, but not really elegant...

**Comment by LinguList** [comment]
Yes, @Anaphory, the idea in the wordlist class is to provide some kind of internal tabular format with languages in the columns, and concepts in the rows, with entries inside. This format seemed useful, since linguists often want that format for their studies. [handling wordlists](http://lingpy.org/tutorial/lingpy.basic.wordlist.html) is a tutorial entry that actually talks about this. So doculect is just a namespace, that could be replaced by any other name (as long as it's case insensitive), while the main semantics is "col".
