### ISSUE TITLE
Documentation and examples for orthography profiles

### ISSUE THREAD

**Issue by argideritzalpea** [lingpy/lingpy#422]
I am attempting to modify the behavior of the alignment functions based on a custom orthography:
In the following example, `lemqeggel` and `l nṭeg g yil` are graphemic, and I would like the alignment model to interpret their sounds based on this custom orthography.
```
import lingpy
import lingpy as lp
from lingpy import *

import re

original = ['lemqeggel', 'l nṭeg g yil']
despaced = [re.sub(" ", "", x) for x in original]

msa = Multiple(despaced)
msa.prog_align()
print(msa) 

['l', 'e', 'm', 'q', 'e', 'gg', 'e', 'l']
['l', '-', 'n', 'ṭ', 'e', 'gg', 'yi', 'l']
```
For example,  I don't want "yi" separated as a single phoneme according to my custom orthographic conventions -> phonemes.

Are there are any documents that show how to do this such that I can change how the prog_align() function works for my example above?

**Comment by LinguList** [comment]
We use ` ` (space) to separate sounds from each other. 

```python
from lingpy import *
seqs = ['l e m q e gg e l', 'l n ṭ e gg y i l']
msa = Mutiple(seqs)
msa.prog_align()
print(msa)
```
output

```
l	e	m	q	e	gg	-	e	l
l	-	n	ṭ	e	gg	y	i	l
```

**Comment by LinguList** [comment]
But I recommend also to not use custom alphabets. Please use IPA. Use [Orthography Profiles](https://digling.org/evobib/?bibtex=Moran2018) to convert your data, as done in [cldf/segments](https://github.com/cldf/segments) or [here](https://digling.org/calc/profile)

**Comment by argideritzalpea** [comment]
Thanks, so before alignment the orthography should be converted to phonemes. 

My application of this tool is actually transcript comparison, and I would like to know when spaces are added in one transcript and not the other.
I am attempting to recover spaces in multi-word alignment as opposed to individual words. For the example above, my actual desired output would be something like the following:
['l', 'e', '*', 'm', 'q', 'e', 'gg', '*', '-', '*', '-', 'e', 'l']
['l', '-', ' ', 'n', 'ṭ', 'e', 'g', ' ', 'g', ' ', 'y', 'i', 'l']
Where '*' means that a space has been detected in the original in the compared transcript.

Is there any way to achieve this, or a special character to stand in for a null?
For example,
`original = ['l e m q e gg e l', 'l _ n ṭ e g _ g _ y i l']`
returns:
```
['-', '-', 'l', 'e', 'm', 'q', 'e', 'gg', 'e', 'l', '-', '-', '-', '-', '-', '-']
['l', '_', 'n', '-', '-', 'ṭ', 'e', 'g', '-', '-', '_', 'g', '_', 'y', 'i', 'l']
```

**Comment by LinguList** [comment]
morpheme separation characters are + (what I suggest) but _ as well (yet
we will discard it), so go for plus for spaces. But this alignment won't
be able to handle it. It is not quite clear what you want to achieve on
the long run from this one example, so please write me an email and
explain in more detail what the goal of alignments is (seems also that
you don't work with multiple but pairwise alignments). Otherwise, I am
feeling that I am guessing and never will know what your real goal is ;)

**Comment by argideritzalpea** [comment]
The goal is to align pairs of sentences for error analysis / comparison of speech recognition transcript gold data vs. predicted data.
The two things I wanted were:
1. capability to run alignment on multi-word pairs
2. ability to control what constituted a phonemic unit

With regards to 1), I discovered this function from the documentation that works for multi-word pairwise alignment:
```
original = ['ugiɣ ad amneɣ allen iw', "ugiɣ ad mmel i ayenni wef"]

# pairwise
out = lingpy.align.pairwise.nw_align(original[0], original[1])

['u', 'g', 'i', 'ɣ', ' ', 'a', 'd', ' ', 'a', 'm', 'n', 'e', 'ɣ', ' ', '-', '-', 'a', 'l', 'l', 'e', 'n', ' ', 'i', '-', 'w', '-', '-']
['u', 'g', 'i', 'ɣ', ' ', 'a', 'd', ' ', '-', 'm', 'm', 'e', 'l', ' ', 'i', ' ', 'a', '-', 'y', 'e', 'n', 'n', 'i', ' ', 'w', 'e', 'f']
```
However, the Multiple class seems able to take care of multiple-phoneme constituents as it aligns, like diphthongs, geminates, etc. On the other hand, I cannot find a Multiple() function that deals with transcripts of multiple words.

So in conclusion:
1. The pairwise function I found (`lingpy.align.pairwise.nw_align`) deals with multiple words (desirable) 
However, if doesn't have a sound model that combine geminates and diphthongs. 

2. From the Multiple class, there was no model that dealt with multiple words. However, using the following code to obtain the alignments, I was able to get geminates and diphthongs in the alignment:
```
despaced = [re.sub(" ", "", x) for x in original]
msa = Multiple(despaced)
msa.prog_align()
aligned = [x.split("\t") for x in msa.__unicode__().split("\n")]
for x in aligned:
    print(x)

['u', 'g', 'i', 'ɣ', 'a', 'd', 'a', 'm', 'n', 'e', 'ɣ', 'a', 'll', 'e', 'n', 'i', 'w', '-', '-']
['u', 'g', 'i', 'ɣ', 'a', 'd', '-', 'mm', '-', '-', '-', 'e', 'l', 'iaye', 'nn', 'i', 'w', 'e', 'f']
``` 
However, this does not preserve where there are spaces in the original.


My desired output is the following:
['u', 'g', 'i', 'ɣ', ' ', 'a', 'd', ' ', 'a', 'm', 'n', 'e', 'ɣ', ' ', 'a', 'll', 'e', 'n', ' ', 'i', '-', 'w', '-', '-']
['u', 'g', 'i', 'ɣ', ' ', 'a', 'd', ' ', '-', 'mm', '-', '-', '-', '-', 'e', 'l', 'iaye', 'nn', '-', 'i', ' ', 'w', 'e', 'f']

I was able to achieve this through custom functions post-processing the output from the Multiple class, but it would be very helpful to know if there is an existing class or function to achieve the goals outlined above.

**Comment by LinguList** [comment]
I think there is a misunderstanding about what the library is supposed to do and what function you actually want to analyze your data.

**Comment by LinguList** [comment]
If you want to compare pairs of sentences with each other, there are probably much different tools better suited for your work. As I mentioned before, we have specific requirements for the representation of strings. You need to replace spaces by an underscore or a plus before doing the analysis. Please read also [this earlier blogpost](https://calc.hypotheses.org/1941) dealing with your problem which I called "sentence alignment". 

As this issue is not related with a problem of the lingpy library in its current state, but rather a question of what best to do when wishing to do a certain analysis, I suggest we close this issue, and you can email me directly, instead of discussing this on github, but please have a look at my post before and know that "multiple" does not refer to "multiple words", but to cases where you align more than two words from different languages with each other.

To have a first look at the basic functions and string representations, I also recommend [lingpy.org](https://lingpy.org) as well as our [tutorial from 2018](https://doi.org/10.1093/jole/lzy006) and the presentation of the algorithm for secondary sequence alignment in my [PhD thesis](http://sequencecomparison.github.io/). If there are more questions, you are cordially invited to write me an email.

**Comment by argideritzalpea** [comment]
Certainly. Thank you for your help and thanks for publishing this work.
