### ISSUE TITLE
lingpy 2.7?

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#425]
I guess it should be lingpy 2.7, but we need a release to cleanup infrastructure/deployment issues:
- [x] switch tests from nose to pytest
- [x] switch CI from travis to GitHub actions
- [x] drop py2 compat
- [x] https://github.com/lingpy/lingpy/issues/417
- [x] https://github.com/lingpy/lingpy/issues/343
- [ ] enhance `RELEASING.md` - such that more steps can be done by maintainers other than @LinguList 
- [x] refactor/simplify `setup.py`

More?

**Comment by LinguList** [comment]
Yes, this is important. I'll need a few days to reflect if we might need
more, but I am rather optimistic we can leave it as is.

**Comment by xrotwang** [comment]
Yes, let me know when the scope of 2.7 in terms of functionality is complete, then I can take care of the scaffolding.

**Comment by xrotwang** [comment]
The current [v2.7 milestone](https://github.com/lingpy/lingpy/milestone/20) looks like there's too much other stuff in there as well.

**Comment by xrotwang** [comment]
And then there's also https://github.com/lingpy/lingpy/milestone/25

**Comment by LinguList** [comment]
Okay, I'll quietly look at it over teh weekend.

**Comment by LinguList** [comment]
I identified a couple of things I'd like to have covered for 2.7, marking them as milestone 2.7. We can also drop some of them, but it would help to reduce open issues to quite some degree, I think, and we could also already decide to drop some things that are probably not needed.

For cython support, I used so far a rather manual procedure of compiling into one verson of Python (3.8 normally) the source files, submitted as pyx-file extension in the folder `algorithm/cython` following the instructions given in the Cython manual with GCC (there's a file called "compilePYX.py" that does this also by selecting the c-header file for Python. 

However, I recently found in a the [cython manual](https://cython.readthedocs.io/en/latest/src/tutorial/pxd_files.html) that one can also just provide the Cython data types by adding a file with extension pxd which contains the types and function call signatures. This seems to be all that is needed, so one can have a normal Python file and a `pxd` file next to it, to allow for a compilation with Cython if it is available, while otherwise using plain Python. I wanted to adapt this solution in any future versions, but so far, my attempts failed, when I tried this by making such a file for `algorithm/cython/calign.py`. 

So I'd say, we can either drop Cython support (lingpy is currently also fast enough anyway), or we could try this apparently easier integration of Cython with a given library.

**Comment by xrotwang** [comment]
From looking at the cython docs myself, I'd opt for dropping it 😀

Johann-Mattis List <notifications@github.com> schrieb am So., 22. Nov.
2020, 18:09:

**Comment by LinguList** [comment]
Yes, in fact, as I mentioned,  haven't even been using it myself for a long time: I forgot to compile it once on a new machine, and didn't realize any performance issues. Dropping is surely a good idea. One COULD even then make the alignment functions less redundant, although I'd not touch them by now, as they are all tested.

**Comment by SimonGreenhill** [comment]
Out of interest has anyone tried lingpy on pypy or numba?

**Comment by PhyloStar** [comment]
Yes. I could work with pypy (it was few years ago).

Best,
Taraka

**Comment by tresoldi** [comment]
I used pypy a couple of months ago. Numba didn't speed it, which was a bit unexpected but it was probably my fault.I could not use the multiprocessing a library the only time I tried (early 2018, i think), because of some incompatibility -- numpy, i think. But pypy worked out of the box.Il 22 Nov 2020 19:39, Taraka Rama <notifications@github.com> ha scritto:

Yes. I could work with pypy (it was few years ago).



Best,

Taraka





On Sun, Nov 22, 2020 at 12:36 PM Simon J Greenhill <notifications@github.com>

wrote:
